import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./LayoutComponents/Header";
import { Alert } from "./UIKit/Alert";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Header />
        {children}
        <Alert />
      </body>
    </html>
  );
}
